# Generated by Django 2.1.7 on 2020-10-06 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100)),
                ('city_district', models.CharField(max_length=100)),
                ('city_population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('indepyear', models.IntegerField()),
                ('population', models.IntegerField()),
                ('localname', models.CharField(max_length=100)),
                ('governmentform', models.CharField(max_length=100)),
                ('headofstate', models.TextField()),
                ('capital', models.IntegerField()),
                ('code2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_language', models.CharField(max_length=50)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldapi.City')),
            ],
        ),
    ]
