# Generated by Django 2.1.7 on 2020-10-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.TextField(default=None)),
                ('city_countrycode', models.CharField(max_length=3)),
                ('city_district', models.TextField(default=None)),
                ('city_population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.TextField(default=None)),
                ('country_continent', models.TextField(default=None)),
                ('country_region', models.TextField(default=None)),
                ('country_surfacearea', models.FloatField(default=None)),
                ('country_indepyear', models.SmallIntegerField(null=True)),
                ('country_population', models.IntegerField(default=None)),
                ('country_lifeexpectancy', models.FloatField(null=True)),
                ('country_localname', models.TextField(default=None)),
                ('country_governmentform', models.TextField(default=None)),
                ('country_headofstate', models.TextField(blank=True, null=True)),
                ('country_code2', models.CharField(default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('countrylanguage_countrycode', models.OneToOneField(db_column='countrylanguage_countrycode', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='worldapi.Country')),
                ('countrylanguage_language', models.TextField(default=None)),
                ('countrylanguage_isofficial', models.BooleanField(default=None)),
                ('countrylanguage_percentage', models.FloatField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='country_capital',
            field=models.ForeignKey(db_column='country_capital', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='worldapi.City'),
        ),
        migrations.AlterUniqueTogether(
            name='countrylanguage',
            unique_together={('countrylanguage_countrycode', 'countrylanguage_language')},
        ),
    ]
